### PR TITLE
Feature/align dart facing interfaces

### PR DESCRIPTION
**Pull request by JordanllHarper**
Creates the `EndpointConfiguration` builder and the `MockzillaConfigurationBuilder` to align with the kotlin interfaces.

Worth noting I wasn't sure on default responses for the builders, and how we might want to document the methods (or if they need documentation at all). It might be helpful for a user if they can see a reference to the `EndpointConfig` model.

### CODE REVIEW

**Comment by JohnKay89** [comment]
@TomRHandcock  @JordanllHarper did you ever discuss whether you need to use a builder pattern here? It doesn't feel very darty to me and you could achieve the same thing with named parameters.

**Comment by JordanllHarper** [comment]
Think the purpose of sticking with the builder pattern is to align with the other platforms.

**Comment by JohnKay89** [comment]
Yeah I think that's fair enough, although in theory if this project exists outside of the scope of apadmi some people will be using it only for flutter

**Comment by TomRHandcock** [comment]
@JohnKay89 Yep that is a strong point, you don't really see builders too much in Dart, I suppose [cascade operators](https://dart.dev/language/operators#cascade-notation) have it covered as part of the language.

@JordanllHarper With that in mind maybe we could forgo the builders and on `MockzillaConfig` just expose a nice constructor and a setter method to add endpoints/logwriters the the underlying list that takes advantage of the cascade operator?

**Comment by JordanllHarper** [comment]
Bit confused, have I got something wrong with that push?

**Comment by TomRHandcock** [comment]
@JordanllHarper I'm on expert on Git but it looks like you re-wrote the history on this branch with that force push. It doesn't look to have caused any problems though. Just so you're aware, if you make changes to the models you'll need to run the code generation as (from what I gather), in Flutter libraries, it is common practice to commit the pre-generated code. Supposedly this is to lesser the burden on consumers.

**Comment by JordanllHarper** [comment]
TomRHandcock I did a rebase and force pushed that. I didn't know about the need for generating files, but that makes sense so that the client doesn't need to initiate that themselves. Hopefully that latest push will work 🤞

**Review by TomRHandcock — APPROVED** [review]

**Pull request merged**
